### ISSUE TITLE
[BUG] Using unquoted spaced value for environment variable fail

### ISSUE THREAD

**Issue by convexshiba** [arabcoders/watchstate#506]
**Describe the bug**

In Webui, change cron expression for import from every 45 to every 15 min

click save leads to

```
[2024-06-23T16:19:50.638774-07:00] http.INFO: 192.168.50.207 - "POST /v1/api/system/env/WS_CRON_PROGRESS_AT HTTP/1.1" 200 119 "http://192.168.50.50:34213/env" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "-" [] []
HTTP: Exception 'Symfony\Component\Dotenv\Exception\FormatException' was thrown unhandled during HTTP boot context. Error 'A value containing spaces must be surrounded by quotes in "/config/config/.env" at line 7.
...RESS_AT=*/15 * * * *\n...
                      ^ line 7 offset 170 @ /vendor/symfony/dotenv/Dotenv.php:546'.
```

Webui no longer loads

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/arabcoders/watchstate/assets/5747393/6e3839e8-a5dc-4f50-beb2-d855996f0aa0)

**Basic report**

```
Paste the system:report output here
```

**Additional context**

Seems the .env is stored as:

```
WS_CRON_PROGRESS_AT=*/15 * * * *
```

Changing to 
```
WS_CRON_PROGRESS_AT="*/15 * * * *"
```

fixes it

**Comment by arabcoders** [comment]
Hi @convexshiba, 

This is as expected, as our underlying env parser library doesn't support unquoted spaced values.

However, the library while nice to have we barely use any of it features, we simply just load them using it, as such i dropped it and replaced it with a local implementation that does support unquoted spaced string, as it's simple line by line parser.

However due to removing this library we lost the following features in env file parsing:
- mutli-line values.
-  shell expansion variables. `WS_TMP_DIR=${WS_TMP_DIR:-WS_DATA_PATH}/tmp_files`
- strict line by line debugger.

While we really don't use any of them, it's good idea to document this in case we later need to know why something doesn't work.

The mentioned changes are happening right now in the dev branch via #507 PR.
